# Generated by Django 4.2.4 on 2023-08-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyupdate',
            name='time_spent',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dailyupdate',
            name='hours_billed',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dailyupdate',
            name='task_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyupdate',
            name='update_text',
            field=models.TextField(null=True),
        ),
    ]
